=== GossJS/15092017-kazi05/part 3/statistics.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT views (most-frequent-ip, deskOS, mobileOS, top-ips)>
        <!ELEMENT most-frequent-ip (#PCDATA)>
        <!ELEMENT deskOS (platform*)>
        <!ELEMENT mobileOS (platform*)>
        <!ELEMENT top-ips (ip*)>
        <!ELEMENT platform (#PCDATA)>
        <!ELEMENT ip EMPTY>
        <!ATTLIST platform name CDATA #REQUIRED>
        <!ATTLIST ip addr CDATA #REQUIRED>
        <!ATTLIST ip frequency CDATA #REQUIRED>

=== GossJS/15092017-kazi05/part 3/statistics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE views PUBLIC "Gadjiev" "statistics.dtd">
<views>
    <most-frequent-ip>077.234.203.101</most-frequent-ip>
    <deskOS>
        <platform name="Windows">87</platform>
        <platform name="Linux">18</platform>
        <platform name="MacOS">6</platform>
    </deskOS>
    <mobileOS>
        <platform name="iPhone">5</platform>
        <platform name="Android">10</platform>
    </mobileOS>
    <top-ips>
        <ip addr="077.234.203.101" frequency="12"/>
        <ip addr="005.144.096.251" frequency="11"/>
        <ip addr="081.222.086.058" frequency="6"/>
        <ip addr="005.164.066.173" frequency="4"/>
        <ip addr="094.019.018.060" frequency="4"/>
    </top-ips>
</views>
